import { useEffect, useState, useRef } from 'react';
import { motion } from 'framer-motion';
import QRCode from 'react-qr-code';
import axios from 'axios';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import useRitualStore from '../store/ritualStore';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const CertificateView = () => {
  const registryId = useRitualStore((state) => state.registryId);
  const certificateUuid = useRitualStore((state) => state.certificateUuid);
  const name = useRitualStore((state) => state.name);
  const confession = useRitualStore((state) => state.confession);
  const severity = useRitualStore((state) => state.severity);
  const tier = useRitualStore((state) => state.tier);
  const status = useRitualStore((state) => state.status);
  const reset = useRitualStore((state) => state.reset);
  const setStep = useRitualStore((state) => state.setStep);
  const [showDelivery, setShowDelivery] = useState(false);
  const [sketchUrl, setSketchUrl] = useState(null);
  const [sketchLoading, setSketchLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [downloadingPdf, setDownloadingPdf] = useState(false);
  const certRef = useRef(null);

  const handleDownloadPdf = async () => {
    if (!certRef.current || downloadingPdf) return;
    setDownloadingPdf(true);
    try {
      const canvas = await html2canvas(certRef.current, {
        scale: 2,
        backgroundColor: '#FFFFFF',
        useCORS: true,
        logging: false,
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = pdfWidth - 20;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let position = 10;
      if (imgHeight > pdfHeight - 20) {
        // Scale down to fit on one page
        const scaleFactor = (pdfHeight - 20) / imgHeight;
        const newWidth = imgWidth * scaleFactor;
        pdf.addImage(
          imgData,
          'PNG',
          (pdfWidth - newWidth) / 2,
          position,
          newWidth,
          imgHeight * scaleFactor
        );
      } else {
        pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
      }
      pdf.save(`KarmaCleanse_${registryId}.pdf`);
    } catch (e) {
      console.error('PDF generation failed:', e);
    } finally {
      setDownloadingPdf(false);
    }
  };

  const verificationUrl = `${window.location.origin}/verify/${registryId}`;

  // Fetch latest cert state from backend so we get sketch_url that was
  // auto-generated by the payment webhook.
  useEffect(() => {
    if (!certificateUuid) return;
    axios
      .get(`${API}/certificate/${certificateUuid}`)
      .then((res) => {
        if (res.data?.sketch_url) {
          setSketchUrl(res.data.sketch_url);
        }
      })
      .catch(() => {
        // silently ignore — local store has the cert anyway
      });
  }, [certificateUuid]);

  // Lazy-load sketch for paid tier only (fallback if webhook hasn't generated yet)
  useEffect(() => {
    if (tier !== 'paid' || !certificateUuid || sketchUrl) return;
    
    setSketchLoading(true);
    axios
      .post(`${API}/sketch/generate/${certificateUuid}`)
      .then((res) => {
        if (res.data?.sketch_url) {
          setSketchUrl(res.data.sketch_url);
        }
      })
      .catch((err) => {
        console.error('Sketch generation failed:', err);
      })
      .finally(() => setSketchLoading(false));
  }, [tier, certificateUuid, sketchUrl]);

  const getSeverityColor = () => {
    if (!severity) return '#525252';
    switch (severity.severity_class) {
      case 'Critical':
        return '#D92D20';
      case 'High':
        return '#B45309';
      case 'Moderate':
        return '#525252';
      default:
        return '#15803D';
    }
  };

  const shareText = `My Karma Cleanse certificate ${registryId} has been issued. Emotional bureaucracy works in mysterious ways.`;

  // Use backend /api/share/{id} URL — it returns HTML with OG meta tags +
  // auto-redirects real users to /verify/{id}. Social media scrapers get a
  // proper preview card with cert image; humans land on the React verification page.
  const shareUrl = `${window.location.origin}/api/share/${registryId}`;

  const shareLinks = {
    telegram: `https://t.me/share/url?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(shareText)}`,
    twitter: `https://twitter.com/intent/tweet?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(shareText)}`,
    whatsapp: `https://wa.me/?text=${encodeURIComponent(shareText + ' ' + shareUrl)}`,
    facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`,
  };

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error('Copy failed:', e);
    }
  };

  const handleStartOver = () => {
    reset();
  };

  if (!severity) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-3xl w-full"
      data-testid="certificate-view"
    >
      {/* Certificate */}
      <div
        ref={certRef}
        className="border-2 p-8 mb-6 relative overflow-hidden"
        style={{
          background: '#FFFFFF',
          borderColor: '#0A0A0A',
        }}
      >
        {/* AI-generated sketch watermark (paid tier only) */}
        {sketchUrl && (
          <div
            className="absolute pointer-events-none"
            style={{
              top: '50%',
              left: '50%',
              transform: 'translate(-50%, -50%)',
              width: '75%',
              maxWidth: '520px',
              opacity: 0.18,
              zIndex: 0,
              mixBlendMode: 'multiply',
            }}
            data-testid="certificate-sketch-watermark"
          >
            <img
              src={sketchUrl}
              alt=""
              className="w-full h-auto"
              style={{ filter: 'grayscale(100%) contrast(1.05)' }}
            />
          </div>
        )}
        
        {/* Sketch loading indicator (subtle) */}
        {sketchLoading && tier === 'paid' && (
          <div
            className="absolute top-3 right-3 text-xs font-mono"
            style={{ color: '#737373', zIndex: 1 }}
          >
            <span className="inline-block animate-pulse">⊙ generating imprint...</span>
          </div>
        )}
        
        {/* Content (above watermark) */}
        <div className="relative" style={{ zIndex: 2 }}>
        {/* Header */}
        <div className="flex items-start justify-between mb-8">
          <div>
            <h1
              className="text-3xl font-black uppercase tracking-tight mb-2"
              style={{ fontFamily: 'Chivo, sans-serif', color: '#0A0A0A' }}
            >
              Karma Cleanse
            </h1>
            <div
              className="text-xs uppercase tracking-widest"
              style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
            >
              Official Certificate v2.1
            </div>
          </div>
          <img
            src="https://static.prod-images.emergentagent.com/jobs/ffea1c83-c6cc-46b9-b35f-810f49dbc24e/images/7c21a7f1a11372181bf010fe1e96f49aaffa8a407a0bc1c67d9e00400f23885a.png"
            alt="Seal"
            className="w-16 h-16"
          />
        </div>

        {/* Registry ID */}
        <div className="mb-6">
          <div
            className="text-xs uppercase font-bold tracking-widest mb-1"
            style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
          >
            Registry ID
          </div>
          <div
            className="text-2xl font-black tracking-tight"
            style={{ fontFamily: 'Chivo, sans-serif', color: '#0A0A0A' }}
          >
            {registryId}
          </div>
        </div>

        {/* Subject */}
        <div className="border-t-2 pt-4 mb-4" style={{ borderColor: '#E5E5DF' }}>
          <div
            className="text-xs uppercase font-bold tracking-widest mb-1"
            style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
          >
            Subject
          </div>
          <div
            className="text-base font-mono"
            style={{ color: '#0A0A0A' }}
          >
            {name || 'Anonymous Entity'}
          </div>
        </div>

        {/* Incident Report (confession) */}
        {confession && (
          <div className="border-t-2 pt-4 mb-4" style={{ borderColor: '#E5E5DF' }}>
            <div
              className="text-xs uppercase font-bold tracking-widest mb-2"
              style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
            >
              Incident Report
            </div>
            <blockquote
              className="text-sm font-mono whitespace-pre-wrap border-l-4 pl-3 py-1"
              style={{
                color: '#0A0A0A',
                borderColor: '#0A0A0A',
                background: 'rgba(244,244,240,0.6)',
              }}
              data-testid="certificate-confession-text"
            >
              {confession}
            </blockquote>
          </div>
        )}

        {/* Severity Classification */}
        <div className="border-t-2 pt-4 mb-4" style={{ borderColor: '#E5E5DF' }}>
          <div
            className="text-xs uppercase font-bold tracking-widest mb-2"
            style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
          >
            Classification
          </div>
          <div
            className="inline-block px-4 py-2 border-2"
            style={{
              borderColor: getSeverityColor(),
              color: getSeverityColor(),
            }}
          >
            <span
              className="text-lg font-black uppercase tracking-wider"
              style={{ fontFamily: 'Chivo, sans-serif' }}
            >
              CLASS {severity.severity_class.toUpperCase()}
            </span>
          </div>
        </div>

        {/* Details Grid */}
        <div className="grid grid-cols-2 gap-4 border-t-2 pt-4 mb-6" style={{ borderColor: '#E5E5DF' }}>
          <div>
            <div
              className="text-xs uppercase font-bold tracking-widest mb-1"
              style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
            >
              Stability
            </div>
            <div
              className="text-sm font-mono"
              style={{ color: '#0A0A0A' }}
            >
              {severity.stability}
            </div>
          </div>
          <div>
            <div
              className="text-xs uppercase font-bold tracking-widest mb-1"
              style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
            >
              Risk Score
            </div>
            <div
              className="text-sm font-mono"
              style={{ color: '#0A0A0A' }}
            >
              {severity.risk_score}/100
            </div>
          </div>
        </div>

        {/* Protocol */}
        <div className="border-t-2 pt-4 mb-6" style={{ borderColor: '#E5E5DF' }}>
          <div
            className="text-xs uppercase font-bold tracking-widest mb-1"
            style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
          >
            Protocol Applied
          </div>
          <div
            className="text-sm font-mono"
            style={{ color: '#0A0A0A' }}
          >
            {severity.protocol}
          </div>
        </div>

        {/* Status */}
        <div className="border-t-2 pt-4 mb-6" style={{ borderColor: '#E5E5DF' }}>
          <div
            className="text-xs uppercase font-bold tracking-widest mb-1"
            style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
          >
            Status
          </div>
          <div
            className="text-sm font-mono uppercase font-bold"
            style={{ color: tier === 'paid' ? '#15803D' : '#B45309' }}
          >
            {status} — {tier} tier
          </div>
        </div>

        {/* QR Code */}
        <div className="border-t-2 pt-6 flex justify-between items-center" style={{ borderColor: '#E5E5DF' }}>
          <div>
            <div
              className="text-xs uppercase font-bold tracking-widest mb-2"
              style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
            >
              Verification
            </div>
            <div
              className="text-xs font-mono break-all max-w-xs"
              style={{ color: '#525252' }}
            >
              {verificationUrl}
            </div>
          </div>
          <div className="border-2 p-2" style={{ borderColor: '#0A0A0A' }}>
            <QRCode value={verificationUrl} size={100} />
          </div>
        </div>
        </div>
      </div>

      {/* Share Section */}
      <div
        className="border-2 p-4 mb-4"
        style={{ background: '#FFFFFF', borderColor: '#0A0A0A' }}
        data-testid="share-section"
      >
        <div
          className="text-xs uppercase font-bold tracking-widest mb-3"
          style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
        >
          Share Certificate
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
          <a
            href={shareLinks.telegram}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center gap-2 py-2 px-3 font-bold uppercase text-xs border-2 transition-colors hover:opacity-80"
            style={{
              background: '#229ED9',
              color: '#FFFFFF',
              borderColor: '#229ED9',
              fontFamily: 'Chivo, sans-serif',
            }}
            data-testid="share-telegram-btn"
          >
            Telegram
          </a>
          <a
            href={shareLinks.twitter}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center gap-2 py-2 px-3 font-bold uppercase text-xs border-2 transition-colors hover:opacity-80"
            style={{
              background: '#000000',
              color: '#FFFFFF',
              borderColor: '#000000',
              fontFamily: 'Chivo, sans-serif',
            }}
            data-testid="share-twitter-btn"
          >
            X / Twitter
          </a>
          <a
            href={shareLinks.whatsapp}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center gap-2 py-2 px-3 font-bold uppercase text-xs border-2 transition-colors hover:opacity-80"
            style={{
              background: '#25D366',
              color: '#FFFFFF',
              borderColor: '#25D366',
              fontFamily: 'Chivo, sans-serif',
            }}
            data-testid="share-whatsapp-btn"
          >
            WhatsApp
          </a>
          <button
            onClick={handleCopyLink}
            className="flex items-center justify-center gap-2 py-2 px-3 font-bold uppercase text-xs border-2 transition-colors hover:opacity-80"
            style={{
              background: copied ? '#15803D' : 'transparent',
              color: copied ? '#FFFFFF' : '#0A0A0A',
              borderColor: copied ? '#15803D' : '#0A0A0A',
              fontFamily: 'Chivo, sans-serif',
            }}
            data-testid="share-copy-btn"
          >
            {copied ? 'Copied ✓' : 'Copy Link'}
          </button>
        </div>
      </div>

      {/* Action Buttons (Premium-only features hidden for Free tier) */}
      <div className="flex flex-col sm:flex-row gap-4 mb-6">
        {tier === 'paid' && (
          <button
            onClick={handleDownloadPdf}
            disabled={downloadingPdf}
            className="flex-1 py-3 font-bold uppercase text-sm border-2 transition-colors disabled:opacity-50"
            style={{
              background: '#0A0A0A',
              color: '#F4F4F0',
              borderColor: '#0A0A0A',
              fontFamily: 'Chivo, sans-serif',
            }}
            data-testid="download-pdf-btn"
          >
            {downloadingPdf ? 'Generating PDF...' : '\u2193 Download PDF'}
          </button>
        )}
        {tier === 'paid' && (
          <button
            onClick={() => setShowDelivery(!showDelivery)}
            className="flex-1 py-3 font-bold uppercase text-sm border-2 transition-colors"
            style={{
              background: 'transparent',
              color: '#0A0A0A',
              borderColor: '#0A0A0A',
              fontFamily: 'Chivo, sans-serif',
            }}
            data-testid="schedule-delivery-btn"
          >
            {showDelivery ? 'Hide Delivery Form' : 'Schedule Email Delivery'}
          </button>
        )}
        {tier === 'free' && (
          <button
            onClick={() => setStep('protocol')}
            className="flex-1 py-3 font-bold uppercase text-sm border-2 transition-colors"
            style={{
              background: '#0A0A0A',
              color: '#F4F4F0',
              borderColor: '#0A0A0A',
              fontFamily: 'Chivo, sans-serif',
            }}
            data-testid="upgrade-to-premium-btn"
          >
            Upgrade to Premium Certificate
          </button>
        )}
        <button
          onClick={handleStartOver}
          className="flex-1 py-3 font-bold uppercase text-sm border-2 transition-colors"
          style={{
            background: 'transparent',
            color: '#0A0A0A',
            borderColor: '#0A0A0A',
            fontFamily: 'Chivo, sans-serif',
          }}
          data-testid="start-over-btn"
        >
          \u2190 Start New Ritual
        </button>
      </div>

      {/* Free tier upgrade notice */}
      {tier === 'free' && (
        <div
          className="border-2 p-4 mb-6"
          style={{
            background: '#FFFFFF',
            borderColor: '#737373',
            borderStyle: 'dashed',
          }}
          data-testid="free-tier-notice"
        >
          <div
            className="text-xs uppercase font-bold tracking-widest mb-2"
            style={{ color: '#B45309', fontFamily: 'IBM Plex Mono, monospace' }}
          >
            Temporary Absolution Receipt
          </div>
          <p className="text-sm font-mono leading-relaxed" style={{ color: '#525252' }}>
            This is a free temporary receipt. It will not be permanently archived,
            cannot be emailed to a recipient, has no AI-generated illustration, and
            offers only limited verification.
          </p>
          <p className="text-sm font-mono mt-2 leading-relaxed" style={{ color: '#525252' }}>
            For permanent records, scheduled delivery, AI illustration, PDF export
            and full institutional verification \u2014 issue a Premium certificate.
          </p>
        </div>
      )}

      {/* Delivery Form */}
      {showDelivery && (
        <motion.div
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: 'auto' }}
          className="border-2 p-6"
          style={{
            background: '#FFFFFF',
            borderColor: '#0A0A0A',
          }}
        >
          <h3
            className="text-xl font-bold uppercase mb-4"
            style={{ fontFamily: 'Chivo, sans-serif', color: '#0A0A0A' }}
          >
            Schedule Email Delivery
          </h3>
          <DeliveryForm />
        </motion.div>
      )}

      {/* Footer */}
      <p
        className="text-xs text-center mt-8"
        style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
      >
        This certificate represents administrative absolution only.
        <br />
        Not legally binding. Emotional bureaucracy since 2026.
        <br />
        <a
          href="/terms"
          target="_blank"
          rel="noopener noreferrer"
          className="underline hover:no-underline mt-2 inline-block"
          style={{ color: '#525252' }}
          data-testid="cert-terms-link"
        >
          Terms & Disclosures
        </a>
      </p>
    </motion.div>
  );
};

const DeliveryForm = () => {
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [hours, setHours] = useState(24);
  const [submitted, setSubmitted] = useState(false);
  const certificateUuid = useRitualStore((state) => state.certificateUuid);

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post(
        `${process.env.REACT_APP_BACKEND_URL}/api/delivery/schedule`,
        {
          certificate_uuid: certificateUuid,
          recipient_email: email,
          message,
          delay_hours: hours,
        }
      );

      setSubmitted(true);
    } catch (error) {
      console.error('Failed to schedule delivery:', error);
      alert('Failed to schedule delivery. Please try again.');
    }
  };

  if (submitted) {
    return (
      <div
        className="text-center py-6 font-mono"
        style={{ color: '#15803D' }}
      >
        ✓ Delivery scheduled successfully!
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label
          className="text-xs uppercase font-bold tracking-widest mb-2 block"
          style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
        >
          Recipient Email
        </label>
        <input
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
          className="w-full border-2 px-4 py-2 text-sm font-mono"
          style={{
            background: '#F4F4F0',
            borderColor: '#0A0A0A',
            color: '#0A0A0A',
          }}
          data-testid="delivery-email-input"
        />
      </div>

      <div>
        <label
          className="text-xs uppercase font-bold tracking-widest mb-2 block"
          style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
        >
          Delay (hours)
        </label>
        <input
          type="number"
          value={hours}
          onChange={(e) => setHours(parseInt(e.target.value))}
          min="1"
          max="168"
          required
          className="w-full border-2 px-4 py-2 text-sm font-mono"
          style={{
            background: '#F4F4F0',
            borderColor: '#0A0A0A',
            color: '#0A0A0A',
          }}
          data-testid="delivery-hours-input"
        />
      </div>

      <div>
        <label
          className="text-xs uppercase font-bold tracking-widest mb-2 block"
          style={{ color: '#737373', fontFamily: 'IBM Plex Mono, monospace' }}
        >
          Optional Message
        </label>
        <textarea
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          rows={3}
          className="w-full border-2 px-4 py-2 text-sm font-mono resize-none"
          style={{
            background: '#F4F4F0',
            borderColor: '#0A0A0A',
            color: '#0A0A0A',
          }}
          data-testid="delivery-message-input"
        />
      </div>

      <button
        type="submit"
        className="w-full py-3 font-bold uppercase text-sm border-2 transition-colors"
        style={{
          background: '#0A0A0A',
          color: '#F4F4F0',
          borderColor: '#0A0A0A',
          fontFamily: 'Chivo, sans-serif',
        }}
        data-testid="submit-delivery-btn"
      >
        Schedule Delivery
      </button>
    </form>
  );
};

export default CertificateView;